---

- name: store facts from all hosts in a variable
  set_fact: host_fact={{hostvars[item]["connection"]|default({}) | combine(hostvars[item]["uname"]|default({})) | combine(hostvars[item]["date"]|default({}))  | combine(hostvars[item]["file_contents"]|default({}))  | combine(hostvars[item]["dmi"]|default({}))  | combine(hostvars[item]["subman"]|default({}))  | combine(hostvars[item]["redhat_release"]|default({}))  | combine(hostvars[item]["cpu"]|default({}))  | combine(hostvars[item]["virt"]|default({}))  | combine(hostvars[item]["virt_what"]|default({}))  | combine(hostvars[item]["etc_release"]|default({}))  | combine(hostvars[item]["redhat_packages"]|default({})) }}
  with_items: "{{groups.alpha}}"
  register: host_facts

- name: parse variable into a list of dictionaries
  set_fact: host_facts="{{ host_facts.results | map(attribute="ansible_facts.host_fact") | list }}"

- name: write the list to a csv
  spit_results:
    name: reporter
    file_path: "{{report_path}}"
    vals: "{{host_facts}}"
    all_vars: "{{hostvars}}"
    fact_names: "{{facts_to_collect}}"
