
---
# This will scan linux systems for JBoss Fuse, ActiveMQ, CXF, Camel or Community  Installations
    - name: Gather jboss.activemq-ver
      raw: FOUND=""; for jar in `find {{scan_dirs}} -type f -xdev -name \*activemq-\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: jboss.activemq-ver
      ignore_errors: yes
      when: '"jboss.activemq-ver" in facts_to_collect'

    - name: Gather jboss.camel-ver
      raw: FOUND=""; for jar in `find {{scan_dirs}} -type f -xdev -name \*camel-core\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: jboss.camel-ver
      ignore_errors: yes
      when: '"jboss.camel-ver" in facts_to_collect'

    - name: Gather jboss.cxf-ver
      raw: FOUND=""; for jar in `find {{scan_dirs}} -type f -xdev -name \*cxf-rt\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: jboss.cxf-ver
      ignore_errors: yes
      when: '"jboss.cxf-ver" in facts_to_collect'
