---

- name: initialize redhat_packages dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) }}"

- name: set gather_is_redhat_gpg fact
  set_fact:
    gather_is_redhat_gpg: "{{ 'redhat-packages.gpg.is_redhat' in facts_to_collect }}"

- name: set gather_num_rh_packages_gpg fact
  set_fact:
    gather_num_rh_packages_gpg: "{{ 'redhat-packages.gpg.num_rh_packages' in facts_to_collect }}"

- name: set gather_num_installed_packages_gpg fact
  set_fact:
    gather_num_installed_packages_gpg: "{{ 'redhat-packages.gpg.num_installed_packages' in facts_to_collect }}"

- name: set gather_last_installed_gpg fact
  set_fact:
    gather_last_installed_gpg: "{{ 'redhat-packages.gpg.last_installed' in facts_to_collect }}"

- name: set gather_last_built_gpg fact
  set_fact:
    gather_last_built_gpg: "{{ 'redhat-packages.gpg.last_built' in facts_to_collect }}"

- name: set gather_redhat_packages_gpg fact
  set_fact:
    gather_redhat_packages_gpg: "{{ gather_is_redhat_gpg or gather_num_rh_packages_gpg or gather_num_installed_packages_gpg or gather_last_installed_gpg or gather_last_built_gpg }}"

- name: initialize redhat-packages.gpg.is_redhat to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: '' }) }}"
  with_items:
  - 'redhat-packages.gpg.is_redhat'
  when: gather_is_redhat_gpg

- name: initialize redhat-packages.gpg.num_rh_packages to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: '' }) }}"
  with_items:
  - 'redhat-packages.gpg.num_rh_packages'
  when: gather_num_rh_packages_gpg

- name: initialize redhat-packages.gpg.num_installed_packages to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: '' }) }}"
  with_items:
  - 'redhat-packages.gpg.num_installed_packages'
  when: gather_num_installed_packages_gpg

- name: initialize redhat-packages.gpg.last_installed to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: '' }) }}"
  with_items:
  - 'redhat-packages.gpg.last_installed'
  when: gather_last_installed_gpg

- name: initialize redhat-packages.gpg.last_built to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: '' }) }}"
  with_items:
  - 'redhat-packages.gpg.last_built'
  when: gather_last_built_gpg

- name: gather redhat-packages fact data
  raw: rpm -qa --qf "%{NAME}|%{VERSION}|%{RELEASE}|%{INSTALLTIME}|%{VENDOR}|%{BUILDTIME}|%{BUILDHOST}|%{SOURCERPM}|%{LICENSE}|%{PACKAGER}|%{INSTALLTIME:date}|%{BUILDTIME:date}|%{DSAHEADER:pgpsig}|%{RSAHEADER:pgpsig}|%{SIGGPG:pgpsig}|%{SIGPGP:pgpsig}|\n"
  register: redhat_packages_results
  ignore_errors: yes
  when: have_rpm and gather_redhat_packages_gpg

- name: add redhat-packages.results to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: redhat_packages_results['stdout_lines'] | default([]) if have_rpm else 'N/A (rpm not found)' }) }}"
  with_items:
  - 'redhat-packages.results'
  when: gather_redhat_packages_gpg

- name: set gather_certs fact
  set_fact:
    gather_certs: "{{ 'redhat-packages.certs' in facts_to_collect }}"

- name: initialize redhat-packages.certs fact
  set_fact:
    redhat_packages_certs: ''
  when: gather_certs

- name: gather redhat-packages.certs fact
  raw: ls /etc/pki/product/ 2> /dev/null| grep '.pem'
  register: redhat_packages_certs_cmd
  ignore_errors: yes
  when: gather_certs

- name: extract result value for redhat-packages.certs
  set_fact:
    redhat_packages_certs: "{{  redhat_packages_certs_cmd['stdout'] | trim | default('error') }}"
  when: 'gather_certs and "stdout" in redhat_packages_certs_cmd'

- name: add redhat-packages.certs to dictionary
  set_fact:
    redhat_packages: "{{ redhat_packages|default({}) | combine({ item: redhat_packages_certs }) }}"
  with_items:
  - 'redhat-packages.certs'
  when: gather_certs
